services:
  auth:
    build:
      context: . # Path to your application (Dockerfile should be here)
      dockerfile: Auth/Dockerfile
    ports:
      - "8002:80" # Expose your application's port
      - "8003:443" # Expose your application's port
    networks:
      - gateway-network
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORTS: 443
      ASPNETCORE_HTTP_PORTS: 80
      ASPNETCORE_Kestrel__Certificates__Default__Password: 1234598765
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/auth.pfx
      Database__ConnectionString: "Server=docker.for.mac.localhost;Initial Catalog=Auth;Persist Security Info=False;User ID=auth-user;Password=XMkHJtcT9RZv4;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=True;Connection Timeout=30;"
      JWTInformation__ValidAudience: "https://localhost:5001"
      JWTInformation__ValidIssuer: "https://localhost:5001"
      JWTInformation__TokenExpiryTimeInHour: "8"
      Cookie__Domain: "localhost"
      Cookie__Path: "/api/v1"
      Cookie__Secure: "True"
      Cookie__SameSite: "Lax"
      Logging__LogLevel__Default: Debug
      AuthTwoFactorAuthentication__EMailVerificationEndpoint : "/api/v1/auth/email-verification"
      AuthenticationType: "JWT"
      PublicUrls : "['/swagger','/api/v1/login,'/api/v1/register']"
      MailSettings__Mail: "mafiagamegroups@gmail.com"
      MailSettings__DisplayName: "Infrastructure Group"
      MailSettings__Host: "smtp.gmail.com"
      MailSettings__Port: 587
      Email_Template__FilePath: "/app/email-template/"
      Email_Template__Variables__CompanyName: "Infrastructure"
      CorsWhiteList: "['http:localhost:8000','https:localhost:80001']"
      SECRET_ENVIRONMENT: "Development"



      Secret_Vault_Name: ${Secret_Vault_Name}
      Secrets__JWTKey_Secret: ${SECRETS__JWTKey_Secret}
      Secrets__ApiKeys: ${SECRETS__ApiKeys}
      Secrets__AuthenticationPassPhrase : ${SECRETS__AuthenticationPassPhrase}
      Secrets__TwoFactorAuthenticationPassPhrase: ${SECRETS__TwoFactorAuthenticationPassPhrase}
      Secrets__EMail_Password: ${SECRETS__EMail_Password}

  gateway:
    build:
      context: . # Path to your application (Dockerfile should be here)
      dockerfile: Gateway/Dockerfile
    ports:
      - "8000:80" # Expose your application's port
      - "8001:443" # Expose your application's port
    networks:
      - gateway-network
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORTS: 443
      ASPNETCORE_HTTP_PORTS: 80
      ASPNETCORE_Kestrel__Certificates__Default__Password: 1234598765
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/auth.pfx
      JWTInformation__ValidAudience: "https://localhost:5001"
      JWTInformation__ValidIssuer: "https://localhost:5001"
      JWTInformation__TokenExpiryTimeInHour: "8"
      Cookie__Domain: "localhost"
      Cookie__Path: "/api/v1"
      Cookie__Secure: "True"
      Cookie__SameSite: "Lax"
      Logging__LogLevel__Default: Debug
      AuthTwoFactorAuthentication__EMailVerificationEndpoint : "/api/v1/auth/email-verification"
      AuthenticationType: "JWT"
      PublicUrls : "['/swagger','/api/v1/auth/login','/api/v1/auth/register']"

      ReverseProxy__Routes__authRoute__ClusterId: auth
      ReverseProxy__Routes__authRoute__Match__Path: api/{version}/auth/{**catch-all} # Specify the path
      ReverseProxy__Routes__authRoute__Transforms__0__PathPattern: /api/{version}/{**catch-all}
      ReverseProxy__Clusters__auth__Destinations__authDestination__Address: http://auth:8002

      Secret_Vault_Name: ${Secret_Vault_Name}
      Secrets__JWTKey_Secret: ${SECRETS__JWTKey_Secret}
      Secrets__ApiKeys: ${SECRETS__ApiKeys}
      Secrets__AuthenticationPassPhrase : ${SECRETS__AuthenticationPassPhrase}
      Secrets__TwoFactorAuthenticationPassPhrase: ${SECRETS__TwoFactorAuthenticationPassPhrase}

networks:
  gateway-network: